CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE
);


CREATE TABLE productscategory (
    id SERIAL PRIMARY KEY,
    category_name TEXT NOT NULL
);

CREATE TABLE era (
    id SERIAL PRIMARY KEY,
    era_name TEXT NOT NULL
);

CREATE TABLE sets (
    id SERIAL PRIMARY KEY,
    set_name TEXT NOT NULL,
    era_id BIGINT NOT NULL,
    FOREIGN KEY (era_id) REFERENCES era(id)
);


CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_name TEXT NOT NULL,
  set_id BIGINT NOT NULL,
  category_id BIGINT NOT NULL,
  quantity NUMERIC,
  price NUMERIC,
  FOREIGN KEY (set_id) REFERENCES sets(id),
  FOREIGN KEY (category_id) REFERENCES productscategory(id)
);


INSERT INTO productscategory (category_name)
VALUES ('Premium Collection'), ('Ultra Premium Collection'), ('Collection Box'), ('Collection Tin'), ('Collection Chest'), ('Booster Pack'), ('Booster Box'), ('Card Storage'), ('Card Protection')

INSERT INTO era (era_name)
VALUES ('Scarlet & Violet'), ('Sword & Shield'), ('Sun & Moon'), ('X & Y'), ('Black & White'), ('Heart Gold & Soul Silver')

INSERT INTO sets (set_name, era_id)
VALUES ('Shrouded Fable', '1'), ('Twilight Masquerade', '1'), ('Temporal Forces', '1'), ('Paldean Fates', '1'), ('Paradox Rift', '1'), ('151', '1'), ('Obsidian Flames', '1'), ('Paldea Evolved', '1'), ('Scarlet & Violet Base Set', '1'), ('Scarlet & Violet Promo', '1')

INSERT INTO sets (set_name, era_id)
VALUES ('Crown Zenith', '2'), ('Silver Tempest', '2'), ('Lost Origin', '2'), ('Pokemon Go', '2'), ('Astral Radiance', '2'), ('Astral Radiance', '2'), ('Brilliant Stars', '2'), ('Fusion Strike', '2'), ('Celebrations', '2'), ('Evolving Skies', '2'), ('Chilling Reign', '2'), ('Battle Styles', '2'), ('Shining Fates', '2'), ('Vivid Voltage', '2'), ('Champions Path', '2'), ('Darkness Ablaze', '2'), ('Rebel Clash', '2'), ('Sword & Shield Base', '2'), ('Sword & Shield Promo', '2')

INSERT INTO products (product_name, set_id, category_id, inventory, price, description)
VALUES ('Booster Pack (10 Cards)', '2', '8', '36', '4', 'One sealed blister booster pack containing 10 random cards with the artwork.'), ('Booster Pack (10 Cards)', '3', '8', '32', '4', 'One sealed blister booster pack containing 10 random cards with the artwork.'), ('Booster Bundle', '4', '8', '9', '24.99', 'Expand your collection with this Booster Bundle containing six booster packs from Pokémon TCG: Scarlet & Violet-Paldean Fates!'), ('Booster Pack (10 Cards)', '4', '8', '4', '4', 'One sealed blister booster pack containing 10 random cards with the artwork.'), ('Booster Pack (10 Cards)', '5', '8', '20', '4', 'One sealed blister booster pack containing 10 random cards with the artwork.'),  ('Booster Pack (10 Cards)', '6', '8', '0', '4', 'One sealed blister booster pack containing 10 random cards with the artwork.'), ('Booster Pack (10 Cards)', '7', '8', '9', '4', 'One sealed blister booster pack containing 10 random cards with the artwork.'), ('Booster Pack (10 Cards)', '8', '8', '9', '4', 'One sealed blister booster pack containing 10 random cards with the artwork.'), ('Checklane Blister', '9', '8', '29', '4.49', 'Pokemon Scarlet & Violet Base Set: Checklane Blister featuring Spidops & Espathra'), ('Booster Pack (10 Cards)', '9', '8', '25', '4', 'One sealed blister booster pack containing 10 random cards with the artwork.'), ('Booster Pack (10 Cards)', '11', '8', '0', '4', 'One sealed blister booster pack containing 10 random cards with the artwork.'), ('Booster Pack (10 Cards)', '12', '8', '26', '4', 'One sealed blister booster pack containing 10 random cards with the artwork.'), ('Booster Pack (10 Cards)', '13', '8', '4', '4', 'One sealed blister booster pack containing 10 random cards with the artwork.'), ('Booster Pack (10 Cards)', '14', '8', '0', '4', 'One sealed blister booster pack containing 10 random cards with the artwork.'), ('Booster Pack (10 Cards)', '15', '8', '10', '4', 'One sealed blister booster pack containing 10 random cards with the artwork.'), ('Booster Pack (10 Cards)', '16', '8', '0', '4', 'One sealed blister booster pack containing 10 random cards with the artwork.'), ('Booster Pack (10 Cards)', '16', '8', '0', '4', 'One sealed blister booster pack containing 10 random cards with the artwork.'), ('Booster Pack (10 Cards)', '17', '8', '17', '4', 'One sealed blister booster pack containing 10 random cards with the artwork.'), ('Booster Pack (10 Cards)', '18', '8', '0', '4', 'One sealed blister booster pack containing 10 random cards with the artwork.'), ('Booster Pack (10 Cards)', '19', '8', '0', '4', 'One sealed blister booster pack containing 10 random cards with the artwork.'), ('Booster Pack (10 Cards)', '20', '8', '0', '4', 'One sealed blister booster pack containing 10 random cards with the artwork.'), ('Booster Pack (10 Cards)', '21', '8', '36', '4', 'One sealed blister booster pack containing 10 random cards with the artwork.'), ('Booster Pack (10 Cards)', '22', '8', '0', '4', 'One sealed blister booster pack containing 10 random cards with the artwork.'), ('Booster Pack (10 Cards)', '23', '8', '36', '4', 'One sealed blister booster pack containing 10 random cards with the artwork.'), ('Booster Pack (10 Cards)', '24', '8', '', '4', 'One sealed blister booster pack containing 10 random cards with the artwork.')